host: "127.0.0.1"
port: "8091"
timeout_retry_period: "1s"
rollbacking_retry_period: "1s"
committing_retry_period: "1s"
aync_committing_retry_period: "1s"
log_delete_period: "24h"
getty_config:
  session_timeout : "20s"
  session_number : 700
  getty_session_param:
    compress_encoding : false
    tcp_no_delay : true
    tcp_keep_alive : true
    keep_alive_period : "120s"
    tcp_r_buf_size : 262144
    tcp_w_buf_size : 524288
    pkg_rq_size : 1024
    pkg_wq_size : 512
    tcp_read_timeout : "1s"
    tcp_write_timeout : "5s"
    wait_timeout : "1s"
    max_msg_len : 4096
    session_name : "seata-server"

store_config:
  max_global_session_size: 512
  max_branch_session_size: 16384